name: pytest and flake8

on: 
  push:
    branches:
      - master
      - test # debug
  pull_request:

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run lint
        run: |
          poetry run flake8 atcoder
      - name: Run test
        run: |
          poetry run pytest tests